dist: xenial   # required for Python >= 3.7
language: python
python:
  - "3.7"

services: postgresql

env:
  - DJANGO=2.1.2

before_install:
  - export DJANGO_SETTINGS_MODULE=final_project_coderslab.settings
  - export PYTHONPATH=$HOME/builds/dawidbudzynski/gameweb_python_django
  - export PIP_USE_MIRRORS=true

install:
  - pip install -r requirements.txt
  - pip install django==$DJANGO --quiet
  - pip install psycopg2 --quiet

before_script:
  - psql -c "CREATE DATABASE game_db;" -U postgres
  - psql -c "CREATE USER dawid_db PASSWORD 'pass_db';" -U postgres
  - psql -c "ALTER USER dawid_db CREATEDB;" -U postgres
  - psql -c "GRANT ALL PRIVILEGES on DATABASE database to dawid_db;" -U postgres
script:
  - python manage.py makemigrations
  - python manage.py migrate
  - python manage.py collectstatic
  - python manage.py test
